base_url = "https://ericscouten.dev"

title = "Eric Scouten :: Developer"
description = "My home for things geeky."
default_language = "en"

theme = "zola-es-theme"

compile_sass = true
build_search_index = true

generate_feed = true
feed_filename = "rss.xml"

[search]
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
smart_punctuation = true

[extra]
endmark = true
es_site = "dev"
fathom_site_id = "WVFRLLAB"
hyvor_site_id = 9759
comments_enabled_default = true
